# Generated by Django 6.0.5 on 2026-05-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_tipi', models.CharField(choices=[('girisimci', 'Mikro-Girişimci / Zanaatkar'), ('musteri', 'Müşteri / Alıcı')], default='musteri', max_length=20)),
                ('biyografi', models.TextField(blank=True, null=True)),
                ('sehir', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('mevcut_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_onerilen_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trend_skoru', models.IntegerField(default=0)),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='urunler/')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
