# Generated by Django 6.0.5 on 2026-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Tüm Kategoriler'), ('gida', 'Doğal Gıda & Zeytinyağı'), ('deri', 'Deri Zanaati / Aksesuar'), ('tekstil', 'Geleneksel Tekstil & Dokuma')], default='genel', max_length=20),
        ),
    ]
