# Generated by Django 6.0.5 on 2026-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0002_urun_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Tüm Kategoriler'), ('gida', 'Doğal Gıda & Zeytinyağı'), ('deri', 'Deri Zanaati / Aksesuar'), ('tekstil', 'Geleneksel Tekstil & Dokuma'), ('ceyiz', 'Çeyizlik Ürünler & El Emeği')], default='genel', max_length=20),
        ),
    ]
