# Generated by Django 6.0.5 on 2026-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0004_alter_urun_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Tüm Ürünler'), ('gida', 'Doğal Gıda Ürünleri'), ('aksesuar', 'Tasarım Aksesuar / Zanaat'), ('ceyiz', 'El Yapımı & Çeyiz Ürünleri')], default='genel', max_length=20),
        ),
    ]
