# Generated by Django 6.0.5 on 2026-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0005_alter_urun_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Girişimci Profili', 'verbose_name_plural': 'Girişimci Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name': 'Zanaat Ürünü', 'verbose_name_plural': 'Zanaat Ürünleri'},
        ),
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, help_text='Başında 0 olmadan telefon numaranızı giriniz.', max_length=15, null=True),
        ),
    ]
