# Generated by Django 6.0.5 on 2026-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0006_alter_profil_options_alter_urun_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Kullanıcı Profili', 'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={'verbose_name': 'Pazaryeri Ürünü', 'verbose_name_plural': 'Pazaryeri Ürünleri'},
        ),
        migrations.AddField(
            model_name='urun',
            name='durum',
            field=models.CharField(choices=[('sifir', 'Sıfır / El Emeği'), ('ikinci_el', 'İkinci El / Kullanılmamış Eşya')], default='sifir', max_length=20),
        ),
        migrations.AlterField(
            model_name='profil',
            name='kullanici_tipi',
            field=models.CharField(choices=[('girisimci', 'Mikro-Girişimci / Zanaatkar'), ('musteri', 'Müşteri / Bireysel Satıcı')], default='musteri', max_length=20),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, help_text='Başında 0 olmadan giriniz.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Tüm Ürünler'), ('gida', 'Doğal Gıda Ürünleri'), ('aksesuar', 'Tasarım Aksesuar & Zanaat'), ('ceyiz', 'El Yapımı & Çeyiz Ürünleri'), ('canta', 'Giyim & Çanta'), ('kitap', 'Kitap & Kültür')], default='genel', max_length=20),
        ),
    ]
