# Generated by Django 6.0.5 on 2026-05-25 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0007_alter_profil_options_alter_urun_options_urun_durum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urun',
            options={},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='biyografi',
        ),
        migrations.AlterField(
            model_name='profil',
            name='kullanici_tipi',
            field=models.CharField(choices=[('zanaatkar', 'Mikro-Girişimci / Zanaatkar'), ('bireysel', 'Bireysel Satıcı (İkinci El)')], default='zanaatkar', max_length=20, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sehir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ai_onerilen_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AI Önerilen Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='durum',
            field=models.CharField(choices=[('sifir', 'Sıfır / El Emeği'), ('ikinci_el', 'İkinci El / Kullanılmış Eşya')], default='sifir', max_length=20, verbose_name='Ürün Durumu'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='urunler/', verbose_name='Ürün Görseli'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('gida', 'Doğal Gıda Ürünleri'), ('aksesuar', 'Tasarım Aksesuar & Zanaat'), ('ceyiz', 'El Yapımı & Çeyiz Ürünleri'), ('canta', 'Giyim & Çanta'), ('kitap', 'Kitap & Kültür')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='mevcut_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Satış Fiyatı (TL)'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='trend_skoru',
            field=models.IntegerField(default=0, verbose_name='Trend / Beğeni Skoru'),
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Mesaj İçeriği')),
                ('tip', models.CharField(choices=[('yorum', 'Kullanıcı Yorumu'), ('soru', 'Satıcıya Soru')], default='yorum', max_length=10, verbose_name='İçerik Tipi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kulucka.urun', verbose_name='İlgili Ürün')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazan Kullanıcı')),
            ],
        ),
    ]
