# Generated by Django 6.0.5 on 2026-05-25 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulucka', '0008_alter_profil_options_alter_urun_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='mevcut_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı (TL)'),
        ),
        migrations.CreateModel(
            name='SepetElemani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=1)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kulucka.urun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet_elemanlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
